### ISSUE TITLE
LSP[svls][Warning] Failed to parse 

### ISSUE THREAD

**Issue by VicoHBB** [dalance/svls#175]
Hi, everyone I'm trying to use svls with LSP, and I compiled and created the files ".svls.toml" and ".svlint.toml" in the path of my project but these errors appears:

```
LSP[svls][Warning] Failed to parse /home/vhbb/PR...IC/dsp-core/.svlint.toml. Enable all lint rules.
```
If I run `svlint` I can see the errors, but they do not appear inside nvim, I'm not sure if I forgot to do something before using it on nvim, I attached my .toml files maybe the error is on it.
- `.svls.toml`
```toml
[systemverilog]
include_paths = ["rtl", "rtl/include"]
defines       = ["DEBUG", "VAR=1"]

[option]
linter = true
```
- `.svlint.toml` here I don't know what I have to put in `exclude_path`
```toml
[option]
exclude_paths = [ ]
prefix_label  = ""

[rules]
blocking_assignment_in_always_ff       = true
case_default                           = true
default_nettype_none                   = false
enum_with_type                         = true
multiline_for_begin                    = true
function_same_as_system_function       = true
function_with_automatic                = true
generate_for_with_label                = true
generate_if_with_label                 = true
keyword_forbidden_generate             = true
generate_keyword_required              = false
genvar_declaration_in_loop             = true
genvar_declaration_out_loop            = false
multiline_if_begin                     = true
inout_with_tri                         = false
input_with_var                         = false
interface_port_with_modport            = false
legacy_always                          = false
level_sensitive_always                 = true
loop_variable_declaration              = true
non_ansi_module                        = true
non_blocking_assignment_in_always_comb = true
output_with_var                        = false
parameter_in_package                   = false
priority_keyword                       = false
tab_character                          = true
unique0_keyword                        = false
unique_keyword                         = false
keyword_forbidden_wire_reg             = true

```
